import type { Candidate, Job, PipelineColumn } from "./types";

export const jobs: Job[] = [
  {
    title: "Senior Frontend Engineer",
    company: "Nexa Fintech",
    place: "TP. Hồ Chí Minh",
    salary: "$2,500 - $3,800",
    match: 96,
    trust: 92,
    tags: ["React", "TypeScript", "Fintech"],
    status: "Ứng tuyển nhanh",
    posted: "2 giờ trước",
    applicants: 31,
    model: "Hybrid",
  },
  {
    title: "Backend Node.js Platform",
    company: "CloudBridge Labs",
    place: "Hà Nội",
    salary: "$2,000 - $3,200",
    match: 91,
    trust: 86,
    tags: ["Node.js", "AWS", "PostgreSQL"],
    status: "Đã lưu",
    posted: "Hôm nay",
    applicants: 22,
    model: "Remote",
  },
  {
    title: "DevOps Engineer",
    company: "Orbit Commerce",
    place: "Đà Nẵng",
    salary: "$1,800 - $2,900",
    match: 84,
    trust: 78,
    tags: ["K8s", "Terraform", "CI/CD"],
    status: "Theo dõi công ty",
    posted: "1 ngày trước",
    applicants: 18,
    model: "Hybrid",
  },
  {
    title: "AI Product Engineer",
    company: "VectorMind AI",
    place: "Remote",
    salary: "$2,800 - $4,500",
    match: 88,
    trust: 89,
    tags: ["Python", "LLM", "React"],
    status: "Hot",
    posted: "3 giờ trước",
    applicants: 44,
    model: "Remote",
  },
  {
    title: "QA Automation Lead",
    company: "ShopGrid",
    place: "TP. Hồ Chí Minh",
    salary: "$1,700 - $2,700",
    match: 82,
    trust: 81,
    tags: ["Playwright", "API Test", "Java"],
    status: "Ứng tuyển",
    posted: "Hôm qua",
    applicants: 15,
    model: "Tại văn phòng",
  },
  {
    title: "Frontend Platform Architect",
    company: "AtlasPay",
    place: "TP. Hồ Chí Minh",
    salary: "$3,500 - $5,200",
    match: 94,
    trust: 91,
    tags: ["React", "Micro Frontends", "Design System"],
    status: "Ứng tuyển nhanh",
    posted: "4 giờ trước",
    applicants: 27,
    model: "Hybrid",
  },
  {
    title: "Go Backend Engineer",
    company: "FinGate",
    place: "Hà Nội",
    salary: "$2,400 - $3,900",
    match: 87,
    trust: 85,
    tags: ["Go", "Kafka", "Payments"],
    status: "Ứng tuyển",
    posted: "Hôm nay",
    applicants: 19,
    model: "Hybrid",
  },
  {
    title: "Senior Mobile Engineer",
    company: "CareLoop Health",
    place: "Remote",
    salary: "$2,200 - $3,600",
    match: 79,
    trust: 83,
    tags: ["React Native", "iOS", "Android"],
    status: "Đã lưu",
    posted: "Hôm nay",
    applicants: 33,
    model: "Remote",
  },
  {
    title: "Security Engineer",
    company: "SecureLayer",
    place: "TP. Hồ Chí Minh",
    salary: "$2,600 - $4,200",
    match: 81,
    trust: 90,
    tags: ["AppSec", "Cloud", "SOC2"],
    status: "Hot",
    posted: "5 giờ trước",
    applicants: 21,
    model: "Hybrid",
  },
  {
    title: "Data Platform Engineer",
    company: "DataNest",
    place: "Hà Nội",
    salary: "$2,300 - $3,700",
    match: 86,
    trust: 82,
    tags: ["Spark", "dbt", "Airflow"],
    status: "Ứng tuyển",
    posted: "1 ngày trước",
    applicants: 24,
    model: "Hybrid",
  },
  {
    title: "Product Designer for Developer Tools",
    company: "CraftBase",
    place: "Remote",
    salary: "$1,900 - $3,100",
    match: 76,
    trust: 88,
    tags: ["UX", "Design System", "SaaS"],
    status: "Theo dõi công ty",
    posted: "2 ngày trước",
    applicants: 12,
    model: "Remote",
  },
  {
    title: "Cloud Solution Architect",
    company: "SkyOps",
    place: "Đà Nẵng",
    salary: "$3,000 - $4,800",
    match: 89,
    trust: 87,
    tags: ["AWS", "K8s", "Terraform"],
    status: "Ứng tuyển nhanh",
    posted: "6 giờ trước",
    applicants: 29,
    model: "Hybrid",
  },
  {
    title: "Fullstack Engineer",
    company: "EduNova",
    place: "TP. Hồ Chí Minh",
    salary: "$1,800 - $2,800",
    match: 83,
    trust: 79,
    tags: ["Next.js", "Node.js", "PostgreSQL"],
    status: "Ứng tuyển",
    posted: "3 ngày trước",
    applicants: 41,
    model: "Tại văn phòng",
  },
  {
    title: "Machine Learning Engineer",
    company: "VectorMind AI",
    place: "Remote",
    salary: "$3,200 - $5,500",
    match: 85,
    trust: 89,
    tags: ["Python", "MLOps", "LLM"],
    status: "Hot",
    posted: "Hôm nay",
    applicants: 52,
    model: "Remote",
  },
  {
    title: "Technical Product Manager",
    company: "Nexa Fintech",
    place: "TP. Hồ Chí Minh",
    salary: "$2,800 - $4,300",
    match: 78,
    trust: 92,
    tags: ["Fintech", "Roadmap", "Analytics"],
    status: "Ứng tuyển",
    posted: "2 ngày trước",
    applicants: 18,
    model: "Hybrid",
  },
  {
    title: "SRE Lead",
    company: "CloudBridge Labs",
    place: "Remote",
    salary: "$3,000 - $4,900",
    match: 88,
    trust: 86,
    tags: ["SLO", "Kubernetes", "Incident"],
    status: "Ứng tuyển nhanh",
    posted: "1 ngày trước",
    applicants: 26,
    model: "Remote",
  },
  {
    title: "Senior Java Engineer",
    company: "CoreBank Systems",
    place: "Hà Nội",
    salary: "$2,200 - $3,500",
    match: 75,
    trust: 84,
    tags: ["Java", "Spring", "Banking"],
    status: "Ứng tuyển",
    posted: "4 ngày trước",
    applicants: 23,
    model: "Tại văn phòng",
  },
  {
    title: "Analytics Engineer",
    company: "RetailVerse",
    place: "TP. Hồ Chí Minh",
    salary: "$1,900 - $3,000",
    match: 82,
    trust: 77,
    tags: ["SQL", "dbt", "Looker"],
    status: "Đã lưu",
    posted: "Hôm qua",
    applicants: 16,
    model: "Hybrid",
  },
  {
    title: "Platform QA Engineer",
    company: "MeshWorks",
    place: "Remote",
    salary: "$1,600 - $2,600",
    match: 80,
    trust: 81,
    tags: ["Playwright", "Performance", "API"],
    status: "Ứng tuyển",
    posted: "2 ngày trước",
    applicants: 14,
    model: "Remote",
  },
  {
    title: "Blockchain Backend Engineer",
    company: "ChainVault",
    place: "TP. Hồ Chí Minh",
    salary: "$2,800 - $4,600",
    match: 73,
    trust: 74,
    tags: ["Rust", "Node.js", "Security"],
    status: "Cần kiểm tra uy tín",
    posted: "Hôm nay",
    applicants: 35,
    model: "Hybrid",
  },
  {
    title: "AI Frontend Engineer",
    company: "PromptFlow",
    place: "Remote",
    salary: "$2,700 - $4,400",
    match: 93,
    trust: 88,
    tags: ["React", "LLM UI", "Streaming"],
    status: "Ứng tuyển nhanh",
    posted: "1 giờ trước",
    applicants: 39,
    model: "Remote",
  },
];

export const companies = [
  { name: "Nexa Fintech", trust: 92, followers: 1240, jobs: 18, field: "Fintech" },
  { name: "CloudBridge Labs", trust: 86, followers: 1020, jobs: 14, field: "Cloud SaaS" },
  { name: "Orbit Commerce", trust: 80, followers: 804, jobs: 9, field: "E-commerce" },
  { name: "VectorMind AI", trust: 89, followers: 1550, jobs: 11, field: "AI Product" },
  { name: "AtlasPay", trust: 91, followers: 1180, jobs: 12, field: "Thanh toán" },
  { name: "FinGate", trust: 85, followers: 940, jobs: 8, field: "Banking API" },
  { name: "CareLoop Health", trust: 83, followers: 720, jobs: 6, field: "HealthTech" },
  { name: "SecureLayer", trust: 90, followers: 680, jobs: 7, field: "Security" },
  { name: "DataNest", trust: 82, followers: 760, jobs: 10, field: "Data Platform" },
  { name: "CraftBase", trust: 88, followers: 640, jobs: 5, field: "Developer Tools" },
  { name: "SkyOps", trust: 87, followers: 830, jobs: 9, field: "Tư vấn Cloud" },
  { name: "EduNova", trust: 79, followers: 520, jobs: 6, field: "EdTech" },
  { name: "CoreBank Systems", trust: 84, followers: 710, jobs: 8, field: "Ngân hàng doanh nghiệp" },
  { name: "RetailVerse", trust: 77, followers: 460, jobs: 4, field: "Retail Analytics" },
  { name: "MeshWorks", trust: 81, followers: 590, jobs: 5, field: "Platform QA" },
  { name: "PromptFlow", trust: 88, followers: 990, jobs: 13, field: "AI Workflow" },
];

export const candidates: Candidate[] = [
  {
    name: "Nguyen Minh Khoa",
    role: "Senior Frontend Engineer",
    job: "React Lead - Fintech",
    match: 96,
    exp: "6 năm",
    salary: "$3.2k",
    stage: "Phỏng vấn 2",
    skills: ["React", "TypeScript", "Next.js"],
    reason: "Kiến trúc React tốt, hiểu domain fintech, kỳ vọng lương khớp range.",
  },
  {
    name: "Tran Bao Anh",
    role: "Backend Engineer",
    job: "Node.js Platform",
    match: 92,
    exp: "5 năm",
    salary: "$2.8k",
    stage: "Shortlist",
    skills: ["Node.js", "AWS", "PostgreSQL"],
    reason: "Kinh nghiệm cloud tốt và điểm ownership API cao.",
  },
  {
    name: "Pham Quoc Viet",
    role: "DevOps Engineer",
    job: "Cloud Infrastructure",
    match: 89,
    exp: "4 năm",
    salary: "$2.4k",
    stage: "Sàng lọc",
    skills: ["K8s", "Terraform", "CI/CD"],
    reason: "Kỹ năng automation tốt, cần thêm kinh nghiệm security.",
  },
  {
    name: "Le Thu Ha",
    role: "QA Automation",
    job: "SDET - E-commerce",
    match: 84,
    exp: "3 năm",
    salary: "$1.9k",
    stage: "Đã ứng tuyển",
    skills: ["Playwright", "API Test", "Java"],
    reason: "Stack automation phù hợp, mức khớp domain trung bình.",
  },
  {
    name: "Do Minh Quan",
    role: "Data Engineer",
    job: "Data Platform Engineer",
    match: 87,
    exp: "5 năm",
    salary: "$2.6k",
    stage: "Shortlist",
    skills: ["Spark", "dbt", "Airflow"],
    reason: "Mạnh về mô hình hóa warehouse và ownership orchestration.",
  },
  {
    name: "Mai Thanh Truc",
    role: "AI Product Engineer",
    job: "AI Product Engineer",
    match: 91,
    exp: "4 năm",
    salary: "$3.4k",
    stage: "Đã ứng tuyển",
    skills: ["Python", "LLM", "React"],
    reason: "Cân bằng giữa prototype AI và triển khai frontend cho product team.",
  },
  {
    name: "Hoang Gia Bao",
    role: "Mobile Lead",
    job: "Senior Mobile Engineer",
    match: 78,
    exp: "6 năm",
    salary: "$2.7k",
    stage: "Sàng lọc",
    skills: ["React Native", "iOS", "Android"],
    reason: "Nền tảng mobile rộng, cần thêm bằng chứng compliance trong healthcare.",
  },
  {
    name: "Nguyen Anh Thu",
    role: "Frontend Platform Architect",
    job: "Frontend Platform Architect",
    match: 94,
    exp: "8 năm",
    salary: "$4.2k",
    stage: "Phỏng vấn 1",
    skills: ["React", "Micro Frontends", "Design System"],
    reason: "Từng thiết kế UI platform dùng chung và roadmap migration.",
  },
  {
    name: "Pham Nhat Linh",
    role: "Security Engineer",
    job: "Security Engineer",
    match: 81,
    exp: "5 năm",
    salary: "$3.1k",
    stage: "Đã ứng tuyển",
    skills: ["AppSec", "Cloud", "SOC2"],
    reason: "Nền tảng cloud AppSec vững và có tài liệu compliance.",
  },
  {
    name: "Tran Duc Huy",
    role: "Go Backend Engineer",
    job: "Go Backend Engineer",
    match: 88,
    exp: "5 năm",
    salary: "$3.0k",
    stage: "Shortlist",
    skills: ["Go", "Kafka", "Payments"],
    reason: "Có kinh nghiệm hệ thống thanh toán throughput cao và dịch vụ event-driven.",
  },
  {
    name: "Le Khanh Vy",
    role: "Product Designer",
    job: "Product Designer for Developer Tools",
    match: 76,
    exp: "4 năm",
    salary: "$2.3k",
    stage: "Đã ứng tuyển",
    skills: ["UX", "Design System", "SaaS"],
    reason: "UX cho developer tool tốt, portfolio cần metric rõ hơn.",
  },
  {
    name: "Vu Tien Dat",
    role: "Cloud Solution Architect",
    job: "Cloud Solution Architect",
    match: 90,
    exp: "7 năm",
    salary: "$4.0k",
    stage: "Phỏng vấn 2",
    skills: ["AWS", "K8s", "Terraform"],
    reason: "Mạnh về cloud governance và các case migration doanh nghiệp.",
  },
  {
    name: "Bui Quang Minh",
    role: "Fullstack Engineer",
    job: "Fullstack Engineer",
    match: 83,
    exp: "4 năm",
    salary: "$2.4k",
    stage: "Đã ứng tuyển",
    skills: ["Next.js", "Node.js", "PostgreSQL"],
    reason: "Triển khai Fullstack SaaS tốt và thiết kế database ổn định.",
  },
  {
    name: "Dang Hoai Nam",
    role: "Machine Learning Engineer",
    job: "Machine Learning Engineer",
    match: 86,
    exp: "5 năm",
    salary: "$4.1k",
    stage: "Sàng lọc",
    skills: ["Python", "MLOps", "LLM"],
    reason: "Có kinh nghiệm triển khai model và đánh giá LLM.",
  },
  {
    name: "Nguyen Phuong Uyen",
    role: "Technical Product Manager",
    job: "Technical Product Manager",
    match: 79,
    exp: "6 năm",
    salary: "$3.6k",
    stage: "Shortlist",
    skills: ["Fintech", "Roadmap", "Analytics"],
    reason: "Ownership roadmap tốt và ra quyết định dựa trên analytics.",
  },
  {
    name: "Vo Thanh Long",
    role: "SRE Lead",
    job: "SRE Lead",
    match: 89,
    exp: "8 năm",
    salary: "$4.3k",
    stage: "Phỏng vấn 1",
    skills: ["SLO", "Kubernetes", "Incident"],
    reason: "Lãnh đạo xử lý incident rõ ràng và có ownership metric reliability.",
  },
  {
    name: "Phan Bao Ngoc",
    role: "Senior Java Engineer",
    job: "Senior Java Engineer",
    match: 75,
    exp: "6 năm",
    salary: "$2.9k",
    stage: "Đã ứng tuyển",
    skills: ["Java", "Spring", "Banking"],
    reason: "Kinh nghiệm Backend phù hợp nhưng bằng chứng cloud migration còn hạn chế.",
  },
  {
    name: "Huynh Minh Tri",
    role: "Analytics Engineer",
    job: "Analytics Engineer",
    match: 82,
    exp: "4 năm",
    salary: "$2.5k",
    stage: "Sàng lọc",
    skills: ["SQL", "dbt", "Looker"],
    reason: "Mạnh về metric layer và ownership BI cho growth team.",
  },
  {
    name: "Ta Ngoc Son",
    role: "Platform QA Engineer",
    job: "Platform QA Engineer",
    match: 80,
    exp: "4 năm",
    salary: "$2.2k",
    stage: "Đã ứng tuyển",
    skills: ["Playwright", "Performance", "API"],
    reason: "Hồ sơ quality engineering rộng, phù hợp platform team.",
  },
  {
    name: "Ly Thanh Phong",
    role: "Blockchain Backend Engineer",
    job: "Blockchain Backend Engineer",
    match: 73,
    exp: "5 năm",
    salary: "$3.5k",
    stage: "Cần xem xét",
    skills: ["Rust", "Node.js", "Security"],
    reason: "Kỹ năng backend low-level tốt, vai trò cần sàng lọc trust kỹ hơn.",
  },
  {
    name: "Trinh Bao Chau",
    role: "AI Frontend Engineer",
    job: "AI Frontend Engineer",
    match: 93,
    exp: "5 năm",
    salary: "$3.8k",
    stage: "Shortlist",
    skills: ["React", "LLM UI", "Streaming"],
    reason: "Mạnh về streaming UI và kinh nghiệm sản phẩm AI workflow.",
  },
];

export const posts = [
  { title: "React Lead - Fintech", status: "Đang tuyển", expiry: "12 ngày", views: "8,920", cvs: 128 },
  { title: "Node.js Platform Engineer", status: "Đang đẩy tin", expiry: "6 ngày", views: "6,140", cvs: 84 },
  { title: "Data Engineer", status: "Hết hạn", expiry: "0 ngày", views: "2,380", cvs: 31 },
  { title: "Junior Tester", status: "Đã khóa", expiry: "18 ngày", views: "1,190", cvs: 14 },
  { title: "Frontend Platform Architect", status: "Đang tuyển", expiry: "21 ngày", views: "7,420", cvs: 96 },
  { title: "Go Backend Engineer", status: "Đang tuyển", expiry: "15 ngày", views: "5,840", cvs: 72 },
  { title: "SRE Lead", status: "Đang đẩy tin", expiry: "9 ngày", views: "6,910", cvs: 68 },
  { title: "Machine Learning Engineer", status: "Đang tuyển", expiry: "19 ngày", views: "9,860", cvs: 141 },
  { title: "Security Engineer", status: "Chờ duyệt", expiry: "4 ngày", views: "3,420", cvs: 37 },
  { title: "Technical Product Manager", status: "Đang tuyển", expiry: "11 ngày", views: "4,780", cvs: 45 },
  { title: "Mobile Lead", status: "Hết hạn", expiry: "0 ngày", views: "2,910", cvs: 26 },
  { title: "AI Frontend Engineer", status: "Đang đẩy tin", expiry: "13 ngày", views: "8,130", cvs: 103 },
];

export const applicantTrend = [
  { day: "T2", applied: 42, shortlist: 20, interviews: 9 },
  { day: "T3", applied: 55, shortlist: 31, interviews: 12 },
  { day: "T4", applied: 49, shortlist: 28, interviews: 11 },
  { day: "T5", applied: 68, shortlist: 39, interviews: 16 },
  { day: "T6", applied: 63, shortlist: 34, interviews: 15 },
  { day: "T7", applied: 76, shortlist: 45, interviews: 18 },
  { day: "CN", applied: 73, shortlist: 43, interviews: 17 },
];

export const chartBars = [
  { label: "13/01", female: 36, male: 78 },
  { label: "Th02", female: 75, male: 95 },
  { label: "Th03", female: 21, male: 41 },
  { label: "Th04", female: 37, male: 79 },
  { label: "Th05", female: 72, male: 98 },
  { label: "Th06", female: 35, male: 65 },
  { label: "Th07", female: 20, male: 46 },
  { label: "Th08", female: 70, male: 92 },
  { label: "Th09", female: 20, male: 54 },
  { label: "Th10", female: 35, male: 65 },
  { label: "Th11", female: 20, male: 47 },
  { label: "31/12", female: 28, male: 50 },
];

export const pipelineSeed: PipelineColumn[] = [
  {
    id: "applied",
    title: "Đã ứng tuyển",
    color: "#3b82f6",
    bg: "#eff6ff",
    items: [
      { id: "p-1", title: "React Lead - 31 CV", person: "Nguyen Minh Khoa", sla: "SLA 1 ngày", tag: "Cần xem xét", match: 96 },
      { id: "p-2", title: "DevOps - 22 CV", person: "Pham Quoc Viet", sla: "SLA 2 ngày", tag: "Match cao", match: 89 },
      { id: "p-3", title: "SDET - 18 CV", person: "Le Thu Ha", sla: "SLA 3 ngày", tag: "Cần xem xét", match: 84 },
      { id: "p-13", title: "Data Engineer - 14 CV", person: "Do Minh Quan", sla: "SLA 4 ngày", tag: "Sàng lọc", match: 82 },
      { id: "p-14", title: "AI Product - 9 CV", person: "Mai Thanh Truc", sla: "SLA hôm nay", tag: "Mới", match: 91 },
      { id: "p-15", title: "Mobile Lead - 11 CV", person: "Hoang Gia Bao", sla: "SLA 5 ngày", tag: "Cần xem xét", match: 78 },
    ],
  },
  {
    id: "shortlisted",
    title: "Shortlist",
    color: "#574bf5",
    bg: "#eef2ff",
    items: [
      { id: "p-4", title: "Bao Anh - Node.js", person: "Tran Bao Anh", sla: "SLA 1 ngày", tag: "Match cao", match: 92 },
      { id: "p-5", title: "Khoa - React Lead", person: "Nguyen Minh Khoa", sla: "SLA hôm nay", tag: "Đặt lịch", match: 96 },
      { id: "p-6", title: "Viet - DevOps", person: "Pham Quoc Viet", sla: "SLA 3 ngày", tag: "Cần xem xét", match: 89 },
      { id: "p-16", title: "Truc - AI Product", person: "Mai Thanh Truc", sla: "SLA 2 ngày", tag: "Portfolio", match: 91 },
    ],
  },
  {
    id: "interview",
    title: "Phỏng vấn",
    color: "#f59e0b",
    bg: "#fffbeb",
    items: [
      { id: "p-7", title: "Khoa - T6 09:00", person: "Nguyen Minh Khoa", sla: "Vòng 1/2", tag: "Đã xác nhận", match: 96 },
      { id: "p-8", title: "Bao Anh - T3 14:00", person: "Tran Bao Anh", sla: "Vòng 1/2", tag: "Chờ phản hồi", match: 92 },
      { id: "p-9", title: "Viet - T5 10:30", person: "Pham Quoc Viet", sla: "Vòng 2/2", tag: "Vòng cuối", match: 89 },
    ],
  },
  {
    id: "offer",
    title: "Offer",
    color: "#10a778",
    bg: "#e7fff7",
    items: [
      { id: "p-10", title: "Frontend Lead", person: "Nguyen Minh Khoa", sla: "Đã gửi Offer", tag: "Đang đàm phán", match: 96 },
      { id: "p-11", title: "Cloud Engineer", person: "Pham Quoc Viet", sla: "Duyệt Offer", tag: "Đã duyệt", match: 89 },
      { id: "p-12", title: "QA Automation", person: "Le Thu Ha", sla: "Chờ phản hồi", tag: "Đang soạn", match: 84 },
    ],
  },
  {
    id: "hired",
    title: "Đã tuyển",
    color: "#0b7f5f",
    bg: "#c7f8e8",
    items: [
      { id: "p-17", title: "Backend Platform", person: "Tran Bao Anh", sla: "Bắt đầu T2", tag: "Onboarding", match: 92 },
      { id: "p-18", title: "Frontend Architect", person: "Nguyen Minh Khoa", sla: "Đã ký hợp đồng", tag: "Hoàn tất", match: 96 },
    ],
  },
];
