import type { Candidate, Job, PipelineColumn } from "./types";

export const jobs: Job[] = [
  {
    title: "Senior Frontend Engineer",
    company: "Nexa Fintech",
    place: "Ho Chi Minh",
    salary: "$2,500 - $3,800",
    match: 96,
    trust: 92,
    tags: ["React", "TypeScript", "Fintech"],
    status: "Apply fast",
    posted: "2h ago",
    applicants: 31,
    model: "Hybrid",
  },
  {
    title: "Backend Node.js Platform",
    company: "CloudBridge Labs",
    place: "Ha Noi",
    salary: "$2,000 - $3,200",
    match: 91,
    trust: 86,
    tags: ["Node.js", "AWS", "PostgreSQL"],
    status: "Saved",
    posted: "Today",
    applicants: 22,
    model: "Remote",
  },
  {
    title: "DevOps Engineer",
    company: "Orbit Commerce",
    place: "Da Nang",
    salary: "$1,800 - $2,900",
    match: 84,
    trust: 78,
    tags: ["K8s", "Terraform", "CI/CD"],
    status: "Follow company",
    posted: "1d ago",
    applicants: 18,
    model: "Hybrid",
  },
  {
    title: "AI Product Engineer",
    company: "VectorMind AI",
    place: "Remote",
    salary: "$2,800 - $4,500",
    match: 88,
    trust: 89,
    tags: ["Python", "LLM", "React"],
    status: "Hot",
    posted: "3h ago",
    applicants: 44,
    model: "Remote",
  },
  {
    title: "QA Automation Lead",
    company: "ShopGrid",
    place: "Ho Chi Minh",
    salary: "$1,700 - $2,700",
    match: 82,
    trust: 81,
    tags: ["Playwright", "API Test", "Java"],
    status: "Apply",
    posted: "Yesterday",
    applicants: 15,
    model: "Onsite",
  },
  {
    title: "Frontend Platform Architect",
    company: "AtlasPay",
    place: "Ho Chi Minh",
    salary: "$3,500 - $5,200",
    match: 94,
    trust: 91,
    tags: ["React", "Micro Frontends", "Design System"],
    status: "Apply fast",
    posted: "4h ago",
    applicants: 27,
    model: "Hybrid",
  },
  {
    title: "Go Backend Engineer",
    company: "FinGate",
    place: "Ha Noi",
    salary: "$2,400 - $3,900",
    match: 87,
    trust: 85,
    tags: ["Go", "Kafka", "Payments"],
    status: "Apply",
    posted: "Today",
    applicants: 19,
    model: "Hybrid",
  },
  {
    title: "Senior Mobile Engineer",
    company: "CareLoop Health",
    place: "Remote",
    salary: "$2,200 - $3,600",
    match: 79,
    trust: 83,
    tags: ["React Native", "iOS", "Android"],
    status: "Saved",
    posted: "Today",
    applicants: 33,
    model: "Remote",
  },
  {
    title: "Security Engineer",
    company: "SecureLayer",
    place: "Ho Chi Minh",
    salary: "$2,600 - $4,200",
    match: 81,
    trust: 90,
    tags: ["AppSec", "Cloud", "SOC2"],
    status: "Hot",
    posted: "5h ago",
    applicants: 21,
    model: "Hybrid",
  },
  {
    title: "Data Platform Engineer",
    company: "DataNest",
    place: "Ha Noi",
    salary: "$2,300 - $3,700",
    match: 86,
    trust: 82,
    tags: ["Spark", "dbt", "Airflow"],
    status: "Apply",
    posted: "1d ago",
    applicants: 24,
    model: "Hybrid",
  },
  {
    title: "Product Designer for Developer Tools",
    company: "CraftBase",
    place: "Remote",
    salary: "$1,900 - $3,100",
    match: 76,
    trust: 88,
    tags: ["UX", "Design System", "SaaS"],
    status: "Follow company",
    posted: "2d ago",
    applicants: 12,
    model: "Remote",
  },
  {
    title: "Cloud Solution Architect",
    company: "SkyOps",
    place: "Da Nang",
    salary: "$3,000 - $4,800",
    match: 89,
    trust: 87,
    tags: ["AWS", "K8s", "Terraform"],
    status: "Apply fast",
    posted: "6h ago",
    applicants: 29,
    model: "Hybrid",
  },
  {
    title: "Fullstack Engineer",
    company: "EduNova",
    place: "Ho Chi Minh",
    salary: "$1,800 - $2,800",
    match: 83,
    trust: 79,
    tags: ["Next.js", "Node.js", "PostgreSQL"],
    status: "Apply",
    posted: "3d ago",
    applicants: 41,
    model: "Onsite",
  },
  {
    title: "Machine Learning Engineer",
    company: "VectorMind AI",
    place: "Remote",
    salary: "$3,200 - $5,500",
    match: 85,
    trust: 89,
    tags: ["Python", "MLOps", "LLM"],
    status: "Hot",
    posted: "Today",
    applicants: 52,
    model: "Remote",
  },
  {
    title: "Technical Product Manager",
    company: "Nexa Fintech",
    place: "Ho Chi Minh",
    salary: "$2,800 - $4,300",
    match: 78,
    trust: 92,
    tags: ["Fintech", "Roadmap", "Analytics"],
    status: "Apply",
    posted: "2d ago",
    applicants: 18,
    model: "Hybrid",
  },
  {
    title: "SRE Lead",
    company: "CloudBridge Labs",
    place: "Remote",
    salary: "$3,000 - $4,900",
    match: 88,
    trust: 86,
    tags: ["SLO", "Kubernetes", "Incident"],
    status: "Apply fast",
    posted: "1d ago",
    applicants: 26,
    model: "Remote",
  },
  {
    title: "Senior Java Engineer",
    company: "CoreBank Systems",
    place: "Ha Noi",
    salary: "$2,200 - $3,500",
    match: 75,
    trust: 84,
    tags: ["Java", "Spring", "Banking"],
    status: "Apply",
    posted: "4d ago",
    applicants: 23,
    model: "Onsite",
  },
  {
    title: "Analytics Engineer",
    company: "RetailVerse",
    place: "Ho Chi Minh",
    salary: "$1,900 - $3,000",
    match: 82,
    trust: 77,
    tags: ["SQL", "dbt", "Looker"],
    status: "Saved",
    posted: "Yesterday",
    applicants: 16,
    model: "Hybrid",
  },
  {
    title: "Platform QA Engineer",
    company: "MeshWorks",
    place: "Remote",
    salary: "$1,600 - $2,600",
    match: 80,
    trust: 81,
    tags: ["Playwright", "Performance", "API"],
    status: "Apply",
    posted: "2d ago",
    applicants: 14,
    model: "Remote",
  },
  {
    title: "Blockchain Backend Engineer",
    company: "ChainVault",
    place: "Ho Chi Minh",
    salary: "$2,800 - $4,600",
    match: 73,
    trust: 74,
    tags: ["Rust", "Node.js", "Security"],
    status: "Review trust",
    posted: "Today",
    applicants: 35,
    model: "Hybrid",
  },
  {
    title: "AI Frontend Engineer",
    company: "PromptFlow",
    place: "Remote",
    salary: "$2,700 - $4,400",
    match: 93,
    trust: 88,
    tags: ["React", "LLM UI", "Streaming"],
    status: "Apply fast",
    posted: "1h ago",
    applicants: 39,
    model: "Remote",
  },
];

export const companies = [
  { name: "Nexa Fintech", trust: 92, followers: 1240, jobs: 18, field: "Fintech" },
  { name: "CloudBridge Labs", trust: 86, followers: 1020, jobs: 14, field: "Cloud SaaS" },
  { name: "Orbit Commerce", trust: 80, followers: 804, jobs: 9, field: "E-commerce" },
  { name: "VectorMind AI", trust: 89, followers: 1550, jobs: 11, field: "AI Product" },
  { name: "AtlasPay", trust: 91, followers: 1180, jobs: 12, field: "Payments" },
  { name: "FinGate", trust: 85, followers: 940, jobs: 8, field: "Banking API" },
  { name: "CareLoop Health", trust: 83, followers: 720, jobs: 6, field: "HealthTech" },
  { name: "SecureLayer", trust: 90, followers: 680, jobs: 7, field: "Security" },
  { name: "DataNest", trust: 82, followers: 760, jobs: 10, field: "Data Platform" },
  { name: "CraftBase", trust: 88, followers: 640, jobs: 5, field: "Developer Tools" },
  { name: "SkyOps", trust: 87, followers: 830, jobs: 9, field: "Cloud Consulting" },
  { name: "EduNova", trust: 79, followers: 520, jobs: 6, field: "EdTech" },
  { name: "CoreBank Systems", trust: 84, followers: 710, jobs: 8, field: "Enterprise Banking" },
  { name: "RetailVerse", trust: 77, followers: 460, jobs: 4, field: "Retail Analytics" },
  { name: "MeshWorks", trust: 81, followers: 590, jobs: 5, field: "Platform QA" },
  { name: "PromptFlow", trust: 88, followers: 990, jobs: 13, field: "AI Workflow" },
];

export const candidates: Candidate[] = [
  {
    name: "Nguyen Minh Khoa",
    role: "Senior Frontend Engineer",
    job: "React Lead - Fintech",
    match: 96,
    exp: "6 years",
    salary: "$3.2k",
    stage: "Interview 2",
    skills: ["React", "TypeScript", "Next.js"],
    reason: "Strong React architecture, fintech domain, salary fits range.",
  },
  {
    name: "Tran Bao Anh",
    role: "Backend Engineer",
    job: "Node.js Platform",
    match: 92,
    exp: "5 years",
    salary: "$2.8k",
    stage: "Shortlisted",
    skills: ["Node.js", "AWS", "PostgreSQL"],
    reason: "Good cloud experience and high API ownership score.",
  },
  {
    name: "Pham Quoc Viet",
    role: "DevOps Engineer",
    job: "Cloud Infrastructure",
    match: 89,
    exp: "4 years",
    salary: "$2.4k",
    stage: "Screening",
    skills: ["K8s", "Terraform", "CI/CD"],
    reason: "Excellent automation skills, needs more security exposure.",
  },
  {
    name: "Le Thu Ha",
    role: "QA Automation",
    job: "SDET - E-commerce",
    match: 84,
    exp: "3 years",
    salary: "$1.9k",
    stage: "Applied",
    skills: ["Playwright", "API Test", "Java"],
    reason: "Automation stack aligns, moderate domain match.",
  },
  {
    name: "Do Minh Quan",
    role: "Data Engineer",
    job: "Data Platform Engineer",
    match: 87,
    exp: "5 years",
    salary: "$2.6k",
    stage: "Shortlisted",
    skills: ["Spark", "dbt", "Airflow"],
    reason: "Strong warehouse modeling and orchestration ownership.",
  },
  {
    name: "Mai Thanh Truc",
    role: "AI Product Engineer",
    job: "AI Product Engineer",
    match: 91,
    exp: "4 years",
    salary: "$3.4k",
    stage: "Applied",
    skills: ["Python", "LLM", "React"],
    reason: "Balanced AI prototyping and frontend delivery for product teams.",
  },
  {
    name: "Hoang Gia Bao",
    role: "Mobile Lead",
    job: "Senior Mobile Engineer",
    match: 78,
    exp: "6 years",
    salary: "$2.7k",
    stage: "Screening",
    skills: ["React Native", "iOS", "Android"],
    reason: "Good mobile breadth, needs stronger healthcare compliance evidence.",
  },
  {
    name: "Nguyen Anh Thu",
    role: "Frontend Platform Architect",
    job: "Frontend Platform Architect",
    match: 94,
    exp: "8 years",
    salary: "$4.2k",
    stage: "Interview 1",
    skills: ["React", "Micro Frontends", "Design System"],
    reason: "Architected shared UI platforms and migration roadmaps.",
  },
  {
    name: "Pham Nhat Linh",
    role: "Security Engineer",
    job: "Security Engineer",
    match: 81,
    exp: "5 years",
    salary: "$3.1k",
    stage: "Applied",
    skills: ["AppSec", "Cloud", "SOC2"],
    reason: "Solid cloud AppSec background with compliance documentation.",
  },
  {
    name: "Tran Duc Huy",
    role: "Go Backend Engineer",
    job: "Go Backend Engineer",
    match: 88,
    exp: "5 years",
    salary: "$3.0k",
    stage: "Shortlisted",
    skills: ["Go", "Kafka", "Payments"],
    reason: "High throughput payment systems and event-driven services.",
  },
  {
    name: "Le Khanh Vy",
    role: "Product Designer",
    job: "Product Designer for Developer Tools",
    match: 76,
    exp: "4 years",
    salary: "$2.3k",
    stage: "Applied",
    skills: ["UX", "Design System", "SaaS"],
    reason: "Good developer tool UX, portfolio needs clearer metrics.",
  },
  {
    name: "Vu Tien Dat",
    role: "Cloud Solution Architect",
    job: "Cloud Solution Architect",
    match: 90,
    exp: "7 years",
    salary: "$4.0k",
    stage: "Interview 2",
    skills: ["AWS", "K8s", "Terraform"],
    reason: "Strong cloud governance and enterprise migration cases.",
  },
  {
    name: "Bui Quang Minh",
    role: "Fullstack Engineer",
    job: "Fullstack Engineer",
    match: 83,
    exp: "4 years",
    salary: "$2.4k",
    stage: "Applied",
    skills: ["Next.js", "Node.js", "PostgreSQL"],
    reason: "Fullstack SaaS delivery with reliable database design.",
  },
  {
    name: "Dang Hoai Nam",
    role: "Machine Learning Engineer",
    job: "Machine Learning Engineer",
    match: 86,
    exp: "5 years",
    salary: "$4.1k",
    stage: "Screening",
    skills: ["Python", "MLOps", "LLM"],
    reason: "Good model deployment and LLM evaluation experience.",
  },
  {
    name: "Nguyen Phuong Uyen",
    role: "Technical Product Manager",
    job: "Technical Product Manager",
    match: 79,
    exp: "6 years",
    salary: "$3.6k",
    stage: "Shortlisted",
    skills: ["Fintech", "Roadmap", "Analytics"],
    reason: "Strong roadmap ownership and analytics-driven decisions.",
  },
  {
    name: "Vo Thanh Long",
    role: "SRE Lead",
    job: "SRE Lead",
    match: 89,
    exp: "8 years",
    salary: "$4.3k",
    stage: "Interview 1",
    skills: ["SLO", "Kubernetes", "Incident"],
    reason: "Clear incident leadership and reliability metric ownership.",
  },
  {
    name: "Phan Bao Ngoc",
    role: "Senior Java Engineer",
    job: "Senior Java Engineer",
    match: 75,
    exp: "6 years",
    salary: "$2.9k",
    stage: "Applied",
    skills: ["Java", "Spring", "Banking"],
    reason: "Backend experience fits, but cloud migration evidence is limited.",
  },
  {
    name: "Huynh Minh Tri",
    role: "Analytics Engineer",
    job: "Analytics Engineer",
    match: 82,
    exp: "4 years",
    salary: "$2.5k",
    stage: "Screening",
    skills: ["SQL", "dbt", "Looker"],
    reason: "Strong metric layer and BI ownership for growth teams.",
  },
  {
    name: "Ta Ngoc Son",
    role: "Platform QA Engineer",
    job: "Platform QA Engineer",
    match: 80,
    exp: "4 years",
    salary: "$2.2k",
    stage: "Applied",
    skills: ["Playwright", "Performance", "API"],
    reason: "Broad quality engineering profile for platform teams.",
  },
  {
    name: "Ly Thanh Phong",
    role: "Blockchain Backend Engineer",
    job: "Blockchain Backend Engineer",
    match: 73,
    exp: "5 years",
    salary: "$3.5k",
    stage: "Review",
    skills: ["Rust", "Node.js", "Security"],
    reason: "Strong low-level backend skills, role trust requires extra screening.",
  },
  {
    name: "Trinh Bao Chau",
    role: "AI Frontend Engineer",
    job: "AI Frontend Engineer",
    match: 93,
    exp: "5 years",
    salary: "$3.8k",
    stage: "Shortlisted",
    skills: ["React", "LLM UI", "Streaming"],
    reason: "Excellent streaming UI and AI workflow product experience.",
  },
];

export const posts = [
  { title: "React Lead - Fintech", status: "Active", expiry: "12 days", views: "8,920", cvs: 128 },
  { title: "Node.js Platform Engineer", status: "Boosting", expiry: "6 days", views: "6,140", cvs: 84 },
  { title: "Data Engineer", status: "Expired", expiry: "0 days", views: "2,380", cvs: 31 },
  { title: "Junior Tester", status: "Locked", expiry: "18 days", views: "1,190", cvs: 14 },
  { title: "Frontend Platform Architect", status: "Active", expiry: "21 days", views: "7,420", cvs: 96 },
  { title: "Go Backend Engineer", status: "Active", expiry: "15 days", views: "5,840", cvs: 72 },
  { title: "SRE Lead", status: "Boosting", expiry: "9 days", views: "6,910", cvs: 68 },
  { title: "Machine Learning Engineer", status: "Active", expiry: "19 days", views: "9,860", cvs: 141 },
  { title: "Security Engineer", status: "Review", expiry: "4 days", views: "3,420", cvs: 37 },
  { title: "Technical Product Manager", status: "Active", expiry: "11 days", views: "4,780", cvs: 45 },
  { title: "Mobile Lead", status: "Expired", expiry: "0 days", views: "2,910", cvs: 26 },
  { title: "AI Frontend Engineer", status: "Boosting", expiry: "13 days", views: "8,130", cvs: 103 },
];

export const applicantTrend = [
  { day: "Mon", applied: 42, shortlist: 20, interviews: 9 },
  { day: "Tue", applied: 55, shortlist: 31, interviews: 12 },
  { day: "Wed", applied: 49, shortlist: 28, interviews: 11 },
  { day: "Thu", applied: 68, shortlist: 39, interviews: 16 },
  { day: "Fri", applied: 63, shortlist: 34, interviews: 15 },
  { day: "Sat", applied: 76, shortlist: 45, interviews: 18 },
  { day: "Sun", applied: 73, shortlist: 43, interviews: 17 },
];

export const chartBars = [
  { label: "13 Jan", female: 36, male: 78 },
  { label: "Feb", female: 75, male: 95 },
  { label: "Mar", female: 21, male: 41 },
  { label: "Apr", female: 37, male: 79 },
  { label: "May", female: 72, male: 98 },
  { label: "Jun", female: 35, male: 65 },
  { label: "Jul", female: 20, male: 46 },
  { label: "Aug", female: 70, male: 92 },
  { label: "Sep", female: 20, male: 54 },
  { label: "Oct", female: 35, male: 65 },
  { label: "Nov", female: 20, male: 47 },
  { label: "31 Dec", female: 28, male: 50 },
];

export const pipelineSeed: PipelineColumn[] = [
  {
    id: "applied",
    title: "Applied",
    color: "#3b82f6",
    bg: "#eff6ff",
    items: [
      { id: "p-1", title: "React Lead - 31 CV", person: "Nguyen Minh Khoa", sla: "SLA 1 day", tag: "Need review", match: 96 },
      { id: "p-2", title: "DevOps - 22 CV", person: "Pham Quoc Viet", sla: "SLA 2 days", tag: "High match", match: 89 },
      { id: "p-3", title: "SDET - 18 CV", person: "Le Thu Ha", sla: "SLA 3 days", tag: "Need review", match: 84 },
      { id: "p-13", title: "Data Engineer - 14 CV", person: "Do Minh Quan", sla: "SLA 4 days", tag: "Screening", match: 82 },
      { id: "p-14", title: "AI Product - 9 CV", person: "Mai Thanh Truc", sla: "SLA today", tag: "New", match: 91 },
      { id: "p-15", title: "Mobile Lead - 11 CV", person: "Hoang Gia Bao", sla: "SLA 5 days", tag: "Need review", match: 78 },
    ],
  },
  {
    id: "shortlisted",
    title: "Shortlisted",
    color: "#574bf5",
    bg: "#eef2ff",
    items: [
      { id: "p-4", title: "Bao Anh - Node.js", person: "Tran Bao Anh", sla: "SLA 1 day", tag: "High match", match: 92 },
      { id: "p-5", title: "Khoa - React Lead", person: "Nguyen Minh Khoa", sla: "SLA today", tag: "Schedule", match: 96 },
      { id: "p-6", title: "Viet - DevOps", person: "Pham Quoc Viet", sla: "SLA 3 days", tag: "Need review", match: 89 },
      { id: "p-16", title: "Truc - AI Product", person: "Mai Thanh Truc", sla: "SLA 2 days", tag: "Portfolio", match: 91 },
    ],
  },
  {
    id: "interview",
    title: "Interview",
    color: "#f59e0b",
    bg: "#fffbeb",
    items: [
      { id: "p-7", title: "Khoa - Fri 09:00", person: "Nguyen Minh Khoa", sla: "Loop 1/2", tag: "Confirmed", match: 96 },
      { id: "p-8", title: "Bao Anh - Tue 14:00", person: "Tran Bao Anh", sla: "Loop 1/2", tag: "Waiting", match: 92 },
      { id: "p-9", title: "Viet - Thu 10:30", person: "Pham Quoc Viet", sla: "Loop 2/2", tag: "Final loop", match: 89 },
    ],
  },
  {
    id: "offer",
    title: "Offer",
    color: "#10a778",
    bg: "#e7fff7",
    items: [
      { id: "p-10", title: "Frontend Lead", person: "Nguyen Minh Khoa", sla: "Offer sent", tag: "Negotiating", match: 96 },
      { id: "p-11", title: "Cloud Engineer", person: "Pham Quoc Viet", sla: "Offer review", tag: "Approved", match: 89 },
      { id: "p-12", title: "QA Automation", person: "Le Thu Ha", sla: "Waiting", tag: "Drafting", match: 84 },
    ],
  },
  {
    id: "hired",
    title: "Hired",
    color: "#0b7f5f",
    bg: "#c7f8e8",
    items: [
      { id: "p-17", title: "Backend Platform", person: "Tran Bao Anh", sla: "Start Mon", tag: "Onboarding", match: 92 },
      { id: "p-18", title: "Frontend Architect", person: "Nguyen Minh Khoa", sla: "Contract signed", tag: "Done", match: 96 },
    ],
  },
];
